spring:
  datasource:
    url: jdbc:postgresql:///${DB_DATABASE:cdg-dev}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      minimum-idle: 2
      maximum-pool-size: 5
      data-source-properties:
        socketFactory: com.google.cloud.sql.postgres.SocketFactory
        cloudSqlInstance: ${DB_CLOUD_SQL_INSTANCE:lively-crane-432311-b0:asia-southeast1:cdg-incentive-dev}
        enableIamAuth: true
        sslmode: disable
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://sts.windows.net/7bc43426-d426-446f-957d-757125ec2693/
          jwk-set-uri: https://login.microsoftonline.com/7bc43426-d426-446f-957d-757125ec2693/discovery/keys